tech_colors ={
    'onwind': '#235ebc',
    'onshore wind': '#235ebc',
    'offwind': '#6895dd',
    'offshore wind': '#6895dd',
    'offwind-ac': '#6895dd',
    'offshore wind (AC)': '#6895dd',
    'offshore wind ac': '#6895dd',
    'offwind-dc': '#74c6f2',
    'offshore wind (DC)': '#74c6f2',
    'offshore wind dc': '#74c6f2',
    'offwind-float': '#b5e2fa',
    'offshore wind (Float)': '#b5e2fa',
    'offshore wind float': '#b5e2fa',
    'hydro': '#298c81',
    'hydro reservoir': '#298c81',
    'ror': '#3dbfb0',
    'run of river': '#3dbfb0',
    'hydroelectricity': '#298c81',
    'PHS': '#51dbcc',
    'hydro+PHS': '#08ad97',
    'solar': '#f9d002',
    'solar PV': '#f9d002',
    'solar-hsat': '#fdb915',
    'solar thermal': '#d7b24c',
    'residential rural solar thermal': '#f1c069',
    'services rural solar thermal': '#eabf61',
    'residential urban decentral solar thermal': '#e5bc5a',
    'services urban decentral solar thermal': '#dfb953',
    'urban central solar thermal': '#d7b24c',
    'solar rooftop': '#ffea80',
    'OCGT': '#e0986c',
    'OCGT marginal': '#e0986c',
    'OCGT-heat': '#e0986c',
    'gas boiler': '#b0904f',
    'gas boilers': '#db6a25',
    'gas boiler marginal': '#db6a25',
    'residential rural gas boiler': '#d4722e',
    'residential urban decentral gas boiler': '#cb7a36',
    'services rural gas boiler': '#c4813f',
    'services urban decentral gas boiler': '#ba8947',
    'urban central gas boiler': '#b0904f',
    'gas': '#e05b09',
    'gas primary': '#e05b09',
    'gas compressing': '#e05b09',
    'fossil gas': '#e05b09',
    'natural gas': '#e05b09',
    'biogas to gas': '#e36311',
    'biogas to gas CC': '#e51245',
    'CCGT': 'lime',
    'CCGT marginal': '#a85522',
    'allam': '#B98F76',
    'gas for industry co2 to atmosphere': '#692e0a',
    'gas for industry co2 to stored': '#8a3400',
    'gas for industry': '#853403',
    'gas for industry CC': '#692e0a',
    'gas pipeline': '#ebbca0',
    'gas pipeline new': '#a87c62',
    'oil': '#c9c9c9',
    'oil primary': '#d2d2d2',
    'oil refining': '#a6a6a6',
    'imported oil': '#a3a3a3',
    'oil boiler': '#9d9d9d',
    'residential rural oil boiler': '#a9a9a9',
    'services rural oil boiler': '#a5a5a5',
    'residential urban decentral oil boiler': '#a1a1a1',
    'urban central oil boiler': '#9d9d9d',
    'services urban decentral oil boiler': '#999999',
    'agriculture machinery oil': '#949494',
    'shipping oil': '#808080',
    'land transport oil': '#afafaf',
    'Nuclear': '#ff8c00',
    'Nuclear marginal': '#ff8c00',
    'nuclear': '#ff8c00',
    'uranium': '#ff8c00',
    'Coal': '#545454',
    'coal': 'black',
    'Coal marginal': '#545454',
    'coal for industry': '#343434',
    'solid': '#545454',
    'Lignite': '#826837',
    'lignite': 'saddlebrown',
    'Lignite marginal': '#826837',
    'biogas': 'darkorange',
    'biomass': '#baa741',
    'solid biomass': 'darkgreen',
    'municipal solid waste': '#91ba41',
    'solid biomass import': '#d5ca8d',
    'solid biomass transport': '#baa741',
    'solid biomass for industry': '#7a6d26',
    'solid biomass for industry CC': '#47411c',
    'solid biomass for industry co2 from atmosphere': '#736412',
    'solid biomass for industry co2 to stored': '#47411c',
    'urban central solid biomass CHP': 'darkgreen',
    'solid biomass OP': '#9d9042',
    'urban central solid biomass CHP CC': '#6c5d28',
    'biomass boiler': '#8A9A5B',
    'residential rural biomass boiler': '#a1a066',
    'residential urban decentral biomass boiler': '#b0b87b',
    'services rural biomass boiler': '#c6cf98',
    'services urban decentral biomass boiler': '#dde5b5',
    'biomass to liquid': '#32CD32',
    'biomass to liquid CC': '#32DDD2',
    'unsustainable solid biomass': '#998622',
    'unsustainable bioliquids': '#32CD32',
    'electrobiofuels': '#de4060',
    'BioSNG': '#123456',
    'solid biomass to hydrogen': '#654321',
    'lines': '#6c9459',
    'transmission lines': '#6c9459',
    'electricity distribution grid': '#97ad8c',
    'low voltage': '#97ad8c',
    'Electric load': '#110d63',
    'electric demand': '#110d63',
    'electricity': '#110d63',
    'industry electricity': '#2d2a66',
    'industry new electricity': '#2d2a66',
    'agriculture electricity': '#494778',
    'battery': '#ace37f',
    'battery storage': '#ace37f',
    'battery charger': 'goldenrod',
    'battery discharger': 'darkgoldenrod',
    'home battery': '#80c944',
    'home battery storage': '#80c944',
    'home battery charger': '#5e8032',
    'home battery discharger': '#3c5221',
    'BEV charger': '#baf238',
    'V2G': '#e5ffa8',
    'land transport EV': '#baf238',
    'land transport demand': '#38baf2',
    'EV battery': '#baf238',
    'water tanks': '#e9977d',
    'residential rural water tanks': '#f7b7a3',
    'services rural water tanks': '#f3afa3',
    'residential urban decentral water tanks': '#f2b2a3',
    'services urban decentral water tanks': '#f1b4a4',
    'urban central water tanks': '#e9977d',
    'hot water storage': '#e69487',
    'hot water charging': '#e8998b',
    'urban central water tanks charger': '#b57a67',
    'residential rural water tanks charger': '#b4887c',
    'residential urban decentral water tanks charger': '#b39995',
    'services rural water tanks charger': '#b3abb0',
    'services urban decentral water tanks charger': '#b3becc',
    'hot water discharging': '#e99c8e',
    'urban central water tanks discharger': '#b9816e',
    'residential rural water tanks discharger': '#ba9685',
    'residential urban decentral water tanks discharger': '#baac9e',
    'services rural water tanks discharger': '#bbc2b8',
    'services urban decentral water tanks discharger': '#bdd8d3',
    'Heat load': '#cc1f1f',
    'heat': '#d15959',
    'heat vent': '#a74747',
    'heat demand': '#cc1f1f',
    'rural heat': '#ff7c7c',
    'residential rural heat': '#ff7c7c',
    'services rural heat': '#ff9c9c',
    'central heat': '#cc1f1f',
    'urban central heat': '#d15959',
    'urban central heat vent': '#a74747',
    'decentral heat': '#750606',
    'residential urban decentral heat': '#a33c3c',
    'services urban decentral heat': '#cc1f1f',
    'low-temperature heat for industry': '#8f2727',
    'process heat': '#ff0000',
    'agriculture heat': '#d9a5a5',
    'heat pumps': '#2fb537',
    'heat pump': '#8B0000',
    'air heat pump': '#8B0000',
    'residential urban decentral air heat pump': '#48f74f',
    'services urban decentral air heat pump': '#5af95d',
    'services rural air heat pump': '#5af95d',
    'urban central air heat pump': '#8B0000',
    'ground heat pump': '#2fb537',
    'residential rural ground heat pump': '#48f74f',
    'residential rural air heat pump': '#48f74f',
    'services rural ground heat pump': '#5af95d',
    'Ambient': '#98eb9d',
    'CHP': 'red',
    'urban central gas CHP': 'red',
    'urban central lignite CHP': '#8d5e56',
    'urban central coal CHP': 'black',
    'CHP CC': 'red',
    'urban central gas CHP CC': 'red',
    'CHP heat': '#8a5751',
    'CHP electric': '#8a5751',
    'district heating': '#e8beac',
    'resistive heater': '#006400',
    'residential rural resistive heater': '#bef5b5',
    'residential urban decentral resistive heater': '#b2f1a9',
    'services rural resistive heater': '#a5ed9d',
    'services urban decentral resistive heater': '#98e991',
    'urban central resistive heater': '#006400',
    'retrofitting': '#8487e8',
    'building retrofitting': '#8487e8',
    'H2 for industry': '#f073da',
    'H2 for shipping': '#ebaee0',
    'H2': '#bf13a0',
    'hydrogen': '#bf13a0',
    'retrofitted H2 boiler': '#e5a0d9',
    'SMR': '#870c71',
    'SMR CC': '#4f1745',
    'H2 liquefaction': '#d647bd',
    'hydrogen storage': '#bf13a0',
    'H2 Store': '#bf13a0',
    'H2 storage': '#bf13a0',
    'land transport fuel cell': '#6b3161',
    'H2 pipeline': '#f081dc',
    'H2 pipeline retrofitted': '#ba99b5',
    'H2 Fuel Cell': '#c251ae',
    'H2 fuel cell': '#c251ae',
    'H2 turbine': '#991f83',
    'H2 Electrolysis': '#ff29d9',
    'H2 electrolysis': '#ff29d9',
    'NH3': '#46caf0',
    'ammonia': '#46caf0',
    'ammonia store': '#00ace0',
    'ammonia cracker': '#87d0e6',
    'Haber-Bosch': '#076987',
    'Sabatier': '#9850ad',
    'methanation': '#c44ce6',
    'methane': '#c44ce6',
    'Fischer-Tropsch': '#25c49a',
    'liquid': '#25c49a',
    'kerosene for aviation': '#a1ffe6',
    'naphtha for industry': '#57ebc4',
    'methanol-to-kerosene': '#C98468',
    'methanol-to-olefins/aromatics': '#FFA07A',
    'Methanol steam reforming': '#FFBF00',
    'Methanol steam reforming CC': '#A2EA8A',
    'methanolisation': '#00FFBF',
    'biomass-to-methanol': '#EAD28A',
    'biomass-to-methanol CC': '#EADBAD',
    'allam methanol': '#B98F76',
    'CCGT methanol': '#B98F76',
    'CCGT methanol CC': '#B98F76',
    'OCGT methanol': '#B98F76',
    'methanol': '#FF7B00',
    'methanol transport': '#FF7B00',
    'shipping methanol': '#468c8b',
    'industry methanol': '#468c8b',
    'CC': '#f29dae',
    'CCS': '#f29dae',
    'CO2 sequestration': '#f29dae',
    'DAC': '#ff5270',
    'co2 stored': '#f2385a',
    'co2 sequestered': '#f2682f',
    'co2': '#f29dae',
    'co2 vent': '#ffd4dc',
    'CO2 pipeline': '#f5627f',
    'process emissions CC': '#000000',
    'process emissions': '#222222',
    'process emissions to stored': '#444444',
    'process emissions to atmosphere': '#888888',
    'oil emissions': '#aaaaaa',
    'shipping oil emissions': '#555555',
    'shipping methanol emissions': '#666666',
    'land transport oil emissions': '#777777',
    'agriculture machinery oil emissions': '#333333',
    'shipping': '#03a2ff',
    'power-to-heat': '#2fb537',
    'power-to-gas': '#c44ce6',
    'power-to-H2': '#ff29d9',
    'power-to-liquid': '#25c49a',
    'gas-to-power/heat': '#ee8340',
    'waste': '#e3d37d',
    'other': '#000000',
    'geothermal': '#ba91b1',
    'geothermal heat': '#ba91b1',
    'geothermal district heat': '#d19D00',
    'geothermal organic rankine cycle': '#ffbf00',
    'AC': '#70af1d',
    'AC-AC': '#70af1d',
    'AC line': '#70af1d',
    'links': '#8a1caf',
    'HVDC links': '#8a1caf',
    'DC': '#8a1caf',
    'DC-DC': '#8a1caf',
    'DC link': '#8a1caf',
    'load': '#111100',
    'waste CHP': '#e3d37d',
    'waste CHP CC': '#e3d3ff',
    'HVC to air': 'k',
    'H2 pipeline (Kernnetz)': '#6b3161',
    'renewable oil': '#c9c9c9',
    'urban central H2 retrofit CHP': 'turquoise',
    'H2 retrofit OCGT': 'seagreen',
    'H2 retrofit CCGT': '#ff0000',
    'H2 OCGT': '#bf13a0',
    'H2 CCGT': '#ff0000',
    'urban central H2 CHP': '#bf13a0',
    'renewable gas': '#e05b09',
    'Solar': '#f9d002',
    'Onshore Wind': '#235ebc',
    'Offshore Wind (DC)': '#74c6f2',
    'Reservoir & Dam': '#298c81',
    'Offshore Wind (AC)': '#6895dd',
    'Run of River': '#3dbfb0',
    'Pumped Hydro Storage': '#51dbcc',
    'Hydrogen Storage': '#bf13a0',
    'Battery Storage': '#ace37f',
    'Open-Cycle Gas': '#e0986c',
    'rural air heat pump': 'salmon',
    'rural biomass boiler': '#8A9A5B',
    'rural gas boiler': '#d4722e',
    'rural ground heat pump': '#FF6347',
    'rural resistive heater': '#3CB371',
    'rural water tanks': '#f7b7a3',
    'rural water tanks charger': '#b3abb0',
    'rural water tanks discharger': '#bbc2b8',
    'urban decentral air heat pump': '#DC143C',
    'urban decentral biomass boiler': '#8A9A5B',
    'urban decentral gas boiler': '#ba8947',
    'urban decentral heat': '#d15959',
    'urban decentral resistive heater': '#32CD32',
    'urban decentral water tanks': '#f2b2a3',
    'urban decentral water tanks charger': '#b39995',
    'urban decentral water tanks discharger': '#bdd8d3',
    'Combined-Cycle Gas': '#a85522',
    'urban central oil CHP': '#c9c9c9',
    'Electricity load': '#110d63',
    'Electricity trade': '#70af1d',
    'Offshore Wind': '#6895dd',
    'urban decentral oil boiler': '#adadad',
    'rural oil boiler': '#adadad',
    'gas CHP': 'red',
    'VRES': 'lightgreen',
    'urban central H2 retrofit OCGT': 'seagreen',
    'load-shedding': 'pink',
    'urban central CHP': 'red',
    'urban central CHP CC': 'red',
    'coal CHP': 'black',
    'lignite CHP': '#8d5e56',
    'biomass CHP': 'darkgreen',
    'oil CHP': '#c9c9c9',
    'biomass CHP CC': '#6c5d28',
    'gas CHP CC': 'red',
    'solid biomass CHP': 'darkgreen',
    'solid biomass CHP CC': '#6c5d28',
    'water tanks charger': '#b57a67',
    'water tanks discharger': '#b9816e',
    'H2 retrofit CHP': 'turquoise',
    'H2 CHP': '#bf13a0'
    }